import { useState } from "react";

function useProfiles() {
  const [profiles, setProfiles] = useState([
    {
      id: 1,
      name: "Aarav Sharma",
      description: "Software Developer",
      image: "https://randomuser.me/api/portraits/men/1.jpg",
      address: "Bengaluru, India",
    },
    {
      id: 2,
      name: "Sanya Singh",
      description: "UI/UX Designer",
      image: "https://randomuser.me/api/portraits/women/2.jpg",
      address: "Mumbai, India",
    },
    {
      id: 3,
      name: "Riya Patel",
      description: "Project Manager",
      image: "https://randomuser.me/api/portraits/women/3.jpg",
      address: "Ahmedabad, India",
    },
    {
      id: 4,
      name: "Karan Verma",
      description: "Backend Developer",
      image: "https://randomuser.me/api/portraits/men/4.jpg",
      address: "Delhi, India",
    },
    {
      id: 5,
      name: "Pooja Nair",
      description: "DevOps Engineer",
      image: "https://randomuser.me/api/portraits/women/5.jpg",
      address: "Kochi, India",
    },
    {
      id: 6,
      name: "Ananya Roy",
      description: "Frontend Developer",
      image: "https://randomuser.me/api/portraits/women/6.jpg",
      address: "Kolkata, India",
    },
    {
      id: 7,
      name: "Raghav Iyer",
      description: "Mobile Developer",
      image: "https://randomuser.me/api/portraits/men/7.jpg",
      address: "Chennai, India",
    },
    {
      id: 8,
      name: "Diya Choudhary",
      description: "Product Designer",
      image: "https://randomuser.me/api/portraits/women/8.jpg",
      address: "Jaipur, India",
    },
    {
      id: 9,
      name: "Vikram Joshi",
      description: "AI Engineer",
      image: "https://randomuser.me/api/portraits/men/9.jpg",
      address: "Pune, India",
    },
    {
      id: 10,
      name: "Isha Gupta",
      description: "Security Specialist",
      image: "https://randomuser.me/api/portraits/women/10.jpg",
      address: "Hyderabad, India",
    },
    {
      id: 11,
      name: "Neha Kapoor",
      description: "Data Scientist",
      image: "https://randomuser.me/api/portraits/women/11.jpg",
      address: "Lucknow, India",
    },
    {
      id: 12,
      name: "Amitabh Das",
      description: "System Analyst",
      image: "https://randomuser.me/api/portraits/men/12.jpg",
      address: "Patna, India",
    },
    {
      id: 13,
      name: "Priya Menon",
      description: "Database Administrator",
      image: "https://randomuser.me/api/portraits/women/13.jpg",
      address: "Thiruvananthapuram, India",
    },
    {
      id: 14,
      name: "Siddharth Malhotra",
      description: "Network Engineer",
      image: "https://randomuser.me/api/portraits/men/14.jpg",
      address: "Chandigarh, India",
    },
    {
      id: 15,
      name: "Kavita Reddy",
      description: "Business Analyst",
      image: "https://randomuser.me/api/portraits/women/15.jpg",
      address: "Bhopal, India",
    },
    {
      id: 16,
      name: "Arjun Mehta",
      description: "Scrum Master",
      image: "https://randomuser.me/api/portraits/men/16.jpg",
      address: "Nagpur, India",
    },
    {
      id: 17,
      name: "Meera Iyer",
      description: "Quality Assurance Engineer",
      image: "https://randomuser.me/api/portraits/women/17.jpg",
      address: "Coimbatore, India",
    },
    {
      id: 18,
      name: "Nikhil Chandra",
      description: "Technical Support Engineer",
      image: "https://randomuser.me/api/portraits/men/18.jpg",
      address: "Visakhapatnam, India",
    },
    {
      id: 19,
      name: "Sneha Agarwal",
      description: "Content Strategist",
      image: "https://randomuser.me/api/portraits/women/19.jpg",
      address: "Indore, India",
    },
    {
      id: 20,
      name: "Rahul Bose",
      description: "Cloud Solutions Architect",
      image: "https://randomuser.me/api/portraits/men/20.jpg",
      address: "Guwahati, India",
    },
    {
      id: 21,
      name: "Anjali Desai",
      description: "Marketing Manager",
      image: "https://randomuser.me/api/portraits/women/21.jpg",
      address: "Surat, India",
    },
    {
      id: 22,
      name: "Vivek Anand",
      description: "Sales Manager",
      image: "https://randomuser.me/api/portraits/men/22.jpg",
      address: "Vadodara, India",
    },
    {
      id: 23,
      name: "Pallavi Joshi",
      description: "Human Resources Manager",
      image: "https://randomuser.me/api/portraits/women/23.jpg",
      address: "Ludhiana, India",
    },
    {
      id: 24,
      name: "Rohan Khanna",
      description: "Financial Analyst",
      image: "https://randomuser.me/api/portraits/men/24.jpg",
      address: "Agra, India",
    },
    {
      id: 25,
      name: "Shreya Ghosh",
      description: "Operations Manager",
      image: "https://randomuser.me/api/portraits/women/25.jpg",
      address: "Nashik, India",
    },
  ]);

  return { profiles, setProfiles };
}

export default useProfiles;
